server:
  port: 6061

spring:

  kafka:
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring:
        json:
          trusted:
            packages: kafka

  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1

SerializationFeature: FAIL_ON_EMPTY_BEANS